import { ShieldAlert } from "lucide-react";

export function AIDisclaimer() {
  return (
    <div className="flex items-start gap-2 rounded-md border border-border bg-muted/40 px-3 py-2 text-xs text-muted-foreground">
      <ShieldAlert className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" />
      <p>
        <strong className="text-foreground">Responsible AI:</strong> Output is generated by an AI model and may be
        inaccurate or biased. Review carefully before sending, sharing, or acting on it. Avoid submitting confidential
        or personal data.
      </p>
    </div>
  );
}
